services:
  mysql:
    image: mysql:8.4
    container_name: obligatorio_bdii_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: obligatorio_bdii
      MYSQL_USER: obligatorio_user
      MYSQL_PASSWORD: obligatorio_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
