spring.application.name=bdii-backend
server.port=8080

# Datos de conexion a MySQL. Spring Boot usa estos valores para crear el DataSource.
spring.datasource.url=jdbc:mysql://localhost:3306/obligatorio_bdii
spring.datasource.username=obligatorio_user
spring.datasource.password=obligatorio_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Evita que Spring intente crear/modificar tablas automaticamente al iniciar.
spring.sql.init.mode=never
